### ISSUE TITLE
My snippets > edit knop

### ISSUE THREAD

**Issue by StefanoGroenland** [mace015/Larago#2]
Op de pagina `My snippets` heb je de button `edit snipet` dit moet `edit snippet` zijn.

**Comment by mace015** [comment]
Fixed in next release.

**Comment by StefanoGroenland** [comment]
## next release =O

![idiot](https://cloud.githubusercontent.com/assets/6575921/12718299/03d4cd66-c8ee-11e5-93d6-eca946e3bd44.png)
